[package]
name = "purple_hammer"
version = "0.1.0"
authors = ["Shtong <shtong@mm.st>"]

[dependencies.irc]
version = "0.11.4"
default-features = false
features = ["encode"]

[dependencies]
yaml-rust = "0.3"
log = "0.3"
log4rs = "0.5"
time = "0.1"